# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x62ooks.proto\"8\n\x0b\x42ookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"\x1b\n\rBookIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"9\n\x0c\x42ookResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t2_\n\x0b\x42ookService\x12&\n\x07\x41\x64\x64\x42ook\x12\x0c.BookRequest\x1a\r.BookResponse\x12(\n\x07GetBook\x12\x0e.BookIdRequest\x1a\r.BookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_BOOKREQUEST']._serialized_start = 15
    _globals['_BOOKREQUEST']._serialized_end = 71
    _globals['_BOOKIDREQUEST']._serialized_start = 73
    _globals['_BOOKIDREQUEST']._serialized_end = 100
    _globals['_BOOKRESPONSE']._serialized_start = 102
    _globals['_BOOKRESPONSE']._serialized_end = 159
    _globals['_BOOKSERVICE']._serialized_start = 161
    _globals['_BOOKSERVICE']._serialized_end = 256
# @@protoc_insertion_point(module_scope)
